### ISSUE TITLE
qwat_od.vw_element_installation : Insert errors

### ISSUE THREAD

**Issue by xaviermenetrey** [qwat/qwat-data-model#94]
Hello

I receive error when I try to insert a new chamber.

SQL below :

```
INSERT INTO qwat_od.vw_element_installation("remark","year",fk_status,fk_precision,fk_distributor,fk_object_reference,name,installation_type,geometry) VALUES
('Chambre du Caudoz',1899,1301,103,2,9003,'S 43','chamber',ST_GeomFromText('POINTZ(540808.9016777200 151776.4339322100 0.0)',21781))
```

I double-checked that all mandatory fields are filled.
Although, I'm getting the following errors :

> ERREUR:  trop de paramètres pour RAISE
CONTEXT:  fonction PL/pgsql qwat_od.ft_node_element_insert(), ligne 21 à RAISE
instruction SQL « INSERT INTO qwat_od.vw_node_element (
			id
			, fk_district
			, fk_pressurezone
			, fk_printmap
			, _printmaps
			, _geometry_alt1_used
			, _geometry_alt2_used
			, _pipe_node_type
			, _pipe_orientation
			, _pipe_schema_visible
			, geometry
			, geometry_alt1
			, geometry_alt2
			, update_geometry_alt1
			, update_geometry_alt2
			, identification
			, fk_distributor
			, fk_status
			, fk_folder
			, fk_locationtype
			, fk_precision
			, fk_precisionalti
			, fk_object_reference
			, altitude
			, year
			, year_end
			, orientation
			, remark
			, schema_force_visible
			, label_1_visible
			, label_1_x
			, label_1_y
			, label_1_rotation
			, label_1_text
			, label_2_visible
			, label_2_x
			, label_2_y
			, label_2_rotation
			, label_2_text
		) VALUES (
			NEW.id 
			, NEW.fk_district
			, NEW.fk_pressurezone
			, NEW.fk_printmap
			, NEW._printmaps
			, NEW._geometry_alt1_used
			, NEW._geometry_alt2_used
			, NEW._pipe_node_type
			, NEW._pipe_orientation
			, NEW._pipe_schema_visible
			, NEW.geometry
			, NEW.geometry_alt1
			, NEW.geometry_alt2
			, NEW.update_geometry_alt1
			, NEW.update_geometry_alt2
			, NEW.identification
			, NEW.fk_distributor
			, NEW.fk_status
			, NEW.fk_folder
			, NEW.fk_locationtype
			, NEW.fk_precision
			, NEW.fk_precisionalti
			, NEW.fk_object_reference
			, NEW.altitude
			, NEW.year
			, NEW.year_end
			, NEW.orientation
			, NEW.remark
			, NEW.schema_force_visible
			, NEW.label_1_visible
			, NEW.label_1_x
			, NEW.label_1_y
			, NEW.label_1_rotation
			, NEW.label_1_text
			, NEW.label_2_visible
			, NEW.label_2_x
			, NEW.label_2_y
			, NEW.label_2_rotation
			, NEW.label_2_text
		) RETURNING id »
fonction PL/pgsql qwat_od.ft_element_installation_insert(), ligne 3 à instruction SQL
********** Error **********

> ERREUR: trop de paramètres pour RAISE
> SQL state: 42601
> Context: fonction PL/pgsql qwat_od.ft_node_element_insert(), ligne 21 à RAISE
> instruction SQL « INSERT INTO qwat_od.vw_node_element (
> 			id
> 			, fk_district
> 			, fk_pressurezone
> 			, fk_printmap
> 			, _printmaps
> 			, _geometry_alt1_used
> 			, _geometry_alt2_used
> 			, _pipe_node_type
> 			, _pipe_orientation
> 			, _pipe_schema_visible
> 			, geometry
> 			, geometry_alt1
> 			, geometry_alt2
> 			, update_geometry_alt1
> 			, update_geometry_alt2
> 			, identification
> 			, fk_distributor
> 			, fk_status
> 			, fk_folder
> 			, fk_locationtype
> 			, fk_precision
> 			, fk_precisionalti
> 			, fk_object_reference
> 			, altitude
> 			, year
> 			, year_end
> 			, orientation
> 			, remark
> 			, schema_force_visible
> 			, label_1_visible
> 			, label_1_x
> 			, label_1_y
> 			, label_1_rotation
> 			, label_1_text
> 			, label_2_visible
> 			, label_2_x
> 			, label_2_y
> 			, label_2_rotation
> 			, label_2_text
> 		) VALUES (
> 			NEW.id 
> 			, NEW.fk_district
> 			, NEW.fk_pressurezone
> 			, NEW.fk_printmap
> 			, NEW._printmaps
> 			, NEW._geometry_alt1_used
> 			, NEW._geometry_alt2_used
> 			, NEW._pipe_node_type
> 			, NEW._pipe_orientation
> 			, NEW._pipe_schema_visible
> 			, NEW.geometry
> 			, NEW.geometry_alt1
> 			, NEW.geometry_alt2
> 			, NEW.update_geometry_alt1
> 			, NEW.update_geometry_alt2
> 			, NEW.identification
> 			, NEW.fk_distributor
> 			, NEW.fk_status
> 			, NEW.fk_folder
> 			, NEW.fk_locationtype
> 			, NEW.fk_precision
> 			, NEW.fk_precisionalti
> 			, NEW.fk_object_reference
> 			, NEW.altitude
> 			, NEW.year
> 			, NEW.year_end
> 			, NEW.orientation
> 			, NEW.remark
> 			, NEW.schema_force_visible
> 			, NEW.label_1_visible
> 			, NEW.label_1_x
> 			, NEW.label_1_y
> 			, NEW.label_1_rotation
> 			, NEW.label_1_text
> 			, NEW.label_2_visible
> 			, NEW.label_2_x
> 			, NEW.label_2_y
> 			, NEW.label_2_rotation
> 			, NEW.label_2_text
> 		) RETURNING id »
> fonction PL/pgsql qwat_od.ft_element_installation_insert(), ligne 3 à instruction SQL

**Comment by 3nids** [comment]
I just tried your command.
I had to give in fk_watertype as it was not defined and the field shall not be null.
Apart from that, it worked.

**Comment by xaviermenetrey** [comment]
Ok I missed fk_watertype.

I added it and ran the SQL INSERT. I still get the error.

The only workaround I found is to INSERT the chamber without geometry and then UPDATE the chamber to add the geometry.

**Comment by 3nids** [comment]
Maybe it's the same source of problem than #93 
Can you try to move the geometry 1 meter away (so there's no pipe at the position) and see if you still get the error?

**Comment by xaviermenetrey** [comment]
I shifted the geometry and it works...

**Comment by 3nids** [comment]
ok, so it's very likely that it's the same issue.

**Comment by 3nids** [comment]
should be fixed now

**Comment by xaviermenetrey** [comment]
Hello, I Tried with the latest fix.

The pipes insertions are OK (#94).

However, I Still get the same issue with the poncutal data.
And I it behaves the same way, when I shift the geometry a little, it works...

**Comment by xaviermenetrey** [comment]
To produce the error :

`INSERT INTO qwat_od.pipe (id, fk_bedding, fk_function, fk_installmethod, fk_material, fk_distributor, fk_precision, fk_status, fk_watertype, pressure_nominal,geometry,"remark", "year") VALUES (8715,102,10003,103,10042,2,1102,1301,1502,NULL,ST_GeomFromText('LINESTRINGZ(542068.8410000000 153926.9720000000 0.0, 542068.6130000000 153926.9520000000 0.0, 542068.3670000000 153926.9590000000 0.0, 542064.8710000000 153927.0510000000 0.0)',21781),'  non',1982)`

`INSERT INTO qwat_od.pipe (id, fk_bedding, fk_function, fk_installmethod, fk_material, fk_distributor, fk_precision, fk_status, fk_watertype, pressure_nominal,geometry,"remark", "year") VALUES (13612,102,10003,103,10042,2,1102,1301,1502,NULL,ST_GeomFromText('LINESTRINGZ(542064.8710000000 153927.0510000000 0.0, 542064.0330000001 153927.0730000000 0.0)',21781),'  non',1982)`

`INSERT INTO qwat_od.vw_element_valve (id, identification,closed,"remark","year",fk_status,fk_precision,fk_precisionalti,altitude,diameter_nominal,fk_valve_type,fk_valve_actuation,fk_valve_function,fk_object_reference,geometry,fk_distributor) VALUES
(2078,'@2078',False,'',1899,1301,103,102,0.0000000000,'150',10002,103,103,9003,ST_GeomFromText('POINTZ(542064.8710000000 153927.0510000000 0.0000000000)',21781),2)`

**Comment by 3nids** [comment]
After fixing missing custom value list, this does not produce any error

INSERT INTO qwat_od.pipe (id, fk_bedding, fk_function, fk_installmethod, fk_material, fk_distributor, fk_precision, fk_status, fk_watertype, pressure_nominal,geometry,"remark", "year") 
VALUES (8715,102,101,103,101,1,1102,1301,1502,NULL,ST_GeomFromText('LINESTRINGZ(542068.8410000000 153926.9720000000 0.0, 542068.6130000000 153926.9520000000 0.0, 542068.3670000000 153926.9590000000 0.0, 542064.8710000000 153927.0510000000 0.0)',21781),' non',1982);

INSERT INTO qwat_od.pipe (id, fk_bedding, fk_function, fk_installmethod, fk_material, fk_distributor, fk_precision, fk_status, fk_watertype, pressure_nominal,geometry,"remark", "year")
VALUES (13612,102,101,103,101,1,1102,1301,1502,NULL,ST_GeomFromText('LINESTRINGZ(542064.8710000000 153927.0510000000 0.0, 542064.0330000001 153927.0730000000 0.0)',21781),' non',1982);

INSERT INTO qwat_od.vw_element_valve (id, identification,closed,"remark","year",fk_status,fk_precision,fk_precisionalti,altitude,diameter_nominal,fk_valve_type,fk_valve_actuation,fk_valve_function,fk_object_reference,geometry,fk_distributor) VALUES
(2078,'@2078',False,'',1899,1301,103,102,0.0000000000,'150',101,103,103,9003,ST_GeomFromText('POINTZ(542064.8710000000 153927.0510000000 0.0000000000)',21781),1);

**Comment by xaviermenetrey** [comment]
Ok, I checked and I have two valves on the same point.
So to reproduce add the valve twice.

`INSERT INTO qwat_od.vw_element_valve (id, identification,closed,"remark","year",fk_status,fk_precision,fk_precisionalti,altitude,diameter_nominal,fk_valve_type,fk_valve_actuation,fk_valve_function,fk_object_reference,geometry,fk_distributor) VALUES (2079,'@2078',False,'',1899,1301,103,102,0.0000000000,'150',10002,103,103,9003,ST_GeomFromText('POINTZ(542064.8710000000 153927.0510000000 0.0000000000)',21781),2)`

**Comment by 3nids** [comment]
well, this is a prerequisite.
you can't have two nodes at the same exact location.

**Comment by xaviermenetrey** [comment]
Ok, I will discuss with the users why they have several nodes on the same point.

Many thanks for your help !
